### ISSUE TITLE
enrollment failure

### ISSUE THREAD

**Issue by ozmoze** [evertrust/horizon-ansible#11]
First of all, thank you for your this ansible pluging.

When trying to enroll a CSR in a decentralized way with csr path, we are getting the below error:

```shell
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: string indices must be integers, not 'str'
fatal: [xxxxxx]: FAILED! => {"msg": "Unexpected failure during module execution: string indices must be integers, not 'str'", "stdout": ""}
```

The full stack trace is:

```shel
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ansible/executor/task_executor.py", line 165, in run
    res = self._execute()
          ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/executor/task_executor.py", line 661, in _execute
    result = self._handler.run(task_vars=vars_copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ansible/collections/ansible_collections/evertrust/horizon/plugins/action/horizon_enroll.py", line 36, in run
    response = client.enroll(**content)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ansible/collections/ansible_collections/evertrust/horizon/plugins/module_utils/horizon.py", line 76, in enroll
    template = self.__get_template(profile, "enroll", "webra")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ansible/collections/ansible_collections/evertrust/horizon/plugins/module_utils/horizon.py", line 284, in __get_template
    return self.post(self.REQUEST_TEMPLATE_URL, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ansible/collections/ansible_collections/evertrust/horizon/plugins/module_utils/horizon.py", line 364, in post
    return self.send('POST', path, json=json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ansible/collections/ansible_collections/evertrust/horizon/plugins/module_utils/horizon.py", line 404, in send
    error_detail = content['detail']
                   ~~~~~~~^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
fatal: [vmwres-pkafka1]: FAILED! => {
    "msg": "Unexpected failure during module execution: string indices must be integers, not 'str'",
    "stdout": ""
}
```

And here is the configuration of our ansible task.

```yaml
- name: Enrolling a certificate in a decentralized way with csr path
    evertrust.horizon.horizon_enroll:
      endpoint: "https://MyHorizonURL/ui#/ra"
      x_api_id: "{{ user_login }}"
      x_api_key: "{{ user_password }}"
      mode: "decentralized"
      ca_bundle: "/etc/ssl/certs/ca-certificates.crt"
      csr:
        src: /tmp/my.csr
      key_type: "rsa-2048"
      profile: "MyProfile"
      subject:
        cn.1: "{{ cert_common_name }}"
      sans:
        dnsname: "{{ cert_common_name }}.domain.com"
      team: "MyTeam"
      contact_email: "MyEmail"
```

**Comment by antoninguyot** [comment]
Hi,

It looks like your Horizon endpoint is incorrect. As per the docs : 
> Your Horizon instance base endpoint. 
It must include the protocol (https://) and no trailing slash nor path.

Should be something like `https://MyHorizonURL`. Please open a ticket at https://support.evertrust.fr if this doesn't fix the issue.

**Comment by ozmoze** [comment]
Thanks for your reply.

when changing URL, I'm getting below error.

```json
FAILED! => {"msg": "Error SEC-AUTH-002 : Invalid credentials or principal does not exist"}
```

I'm sure about my credentials are correct so I will check with evertrust
